'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace EMSWeb

    Partial Public Class FReport

        '''<summary>
        '''div2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ReportTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ReportTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SearchPanels control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SearchPanels As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''UBRLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UBRLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UBRs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UBRs As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblAllDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAllDescription As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''Requestees control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Requestees As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''filterWrapper control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents filterWrapper As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''FilterBoxControl control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents FilterBoxControl As Global.System.Web.UI.UserControl

        '''<summary>
        '''ExportUpdatePanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExportUpdatePanel As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''EditorDataSource control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents EditorDataSource As Global.System.Web.UI.WebControls.SqlDataSource

        '''<summary>
        '''listExportFormat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents listExportFormat As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''SourceDataNotesPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SourceDataNotesPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lplHeaderLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lplHeaderLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SourceLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SourceLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''NotesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents NotesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''VariancesPanel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VariancesPanel As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''rpHeaderLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpHeaderLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''OptionsHeaderLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents OptionsHeaderLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''PeriodRadio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PeriodRadio As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''DropDownList_Period1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownList_Period1 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''DropDownList_Period2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DropDownList_Period2 As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''CountryRadio control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents CountryRadio As Global.System.Web.UI.WebControls.RadioButtonList

        '''<summary>
        '''SubmitVariances control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SubmitVariances As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''VariancesLabel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents VariancesLabel As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hdnShowGridView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnShowGridView As Global.System.Web.UI.HtmlControls.HtmlInputHidden

        '''<summary>
        '''hdnExportReportType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hdnExportReportType As Global.System.Web.UI.HtmlControls.HtmlInputHidden
    End Class
End Namespace
